<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvaE0+IiSlFUEoNuCjeBT'."\n".'QABKKOQo3jLlJXI47sCxexaC+1vvR27PKDwCfiivRczI+7OecL+hYyix8DzA9Ut2'."\n".'CSfxS7WM8hZR2ykmux2JFrqCD83npB9dkg/dEP/EJbF+FDIU/2MS5EfAj68uy16k'."\n".'ff67UMdSLAbY/VoBMvyeAZkeBm3icwgUXTt+6df7fQap/O0YLedFTbpiKbW5WT+I'."\n".'LtMCz6YycQOcdhNMLqh9jdtFc4wYa6xCm0SPxyvSFC1/rpQj7uKfsCPfBbGIJM0P'."\n".'bbv7JtwfbDiBl8SfSrdIl6zFAcq1+dB+w4pI5Eh7zlc0PYnQuX7AXSU95PelZIDa'."\n".'eQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
