<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3SwKYNS\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3SwKYNS/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3SwKYNS.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3SwKYNS\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3SwKYNS\appAppKernelProdContainer([
    'container.build_hash' => '3SwKYNS',
    'container.build_id' => 'cd1fd052',
    'container.build_time' => 1744915560,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3SwKYNS');
