<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZiGgDKI\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZiGgDKI/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZiGgDKI.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZiGgDKI\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerZiGgDKI\appAppKernelDevDebugContainer([
    'container.build_hash' => 'ZiGgDKI',
    'container.build_id' => 'd39e1631',
    'container.build_time' => 1744923265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZiGgDKI');
